config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: [:index] do
    post :parse_categories, on: :collection
  end

  scope path: '/enter', controller: 'enter' do 
    get :login
    post :check
    delete :destroy
  end

  resources :users

  scope path: "videos", controller: "videos" do
    get "/" => :index, as: "videos"
    get :newitems
    post :get_video_info
    get :parse_trends
    delete "/" => :destroy
  end

  get "success" => "videos#success"

  root :to => "enter#login"

end

app/models/video.rb
class Video < ActiveRecord::Base
	extend ParseTrends
	belongs_to :channel
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  skip_before_filter :check_user, only: [:success]

  ITEMS_PER_PAGE = 16

  # GET SUCCESS
  def success
  end
  

  def index
    @videos = current_user.videos.order("views DESC").limit(ITEMS_PER_PAGE)
    @categories = current_user.videos.group_by(&:category_id).map { |f| Category.find_by_category_id(f[0]) }
    @videos = @videos.where(category_id: params[:category_id].to_i) if params[:category_id]
  end

  def newitems
    @videos = current_user.videos.order("views DESC").offset(params[:page].to_i * ITEMS_PER_PAGE).limit(ITEMS_PER_PAGE)
    right = ITEMS_PER_PAGE - @videos.count > 0 ? false : true
    response.headers['permit_to_scroll'] = "#{right}"
    render partial: "video_list"
  end

  def get_video_info
    # Set last categories for user
    if current_user.my_category
      current_user.my_category.set_new_categories(params[:category_ids])
    else
       current_user.build_my_category(list_categories: params[:category_ids].join(",")).save
    end
    
    # THANK YOU TO MY FRIENDS HEROKU
    # I CANT DEPLOY FUCKING APP, BECAUSE OF GREEDY REDIS
    # THANK YOU!!!!!  
    #YoutubeTrendsWorker.perform_async(params, session[:user_id])
    Video.parse_trends(params, session[:user_id])
    #Video.parse_trends(params, session[:user_id])
    redirect_to videos_path
  end

  def parse_trends
    myCat = current_user.my_category
    @categories = myCat ? myCat.list_categories : []
  end

  def destroy
    if params[:category_id]
      videos = current_user.videos.where(category_id: params[:category_id].to_i)
    else
      videos = current_user.videos
    end
    videos.destroy_all
    redirect_to videos_path
  end
  
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :channel_id %><br>
    <%= f.text_field :channel_id %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :href %><br>
    <%= f.text_field :href %>
  </div>
  <div class="field">
    <%= f.label :views %><br>
    <%= f.number_field :views %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/_video_item.html.erb
<div class="video-item">
    <p>
        <%= link_to video.href, class: "link-video", target: "_blank" do %>
            <%= image_tag video.thumbnail %>
            <span><%= video.title %></span>
        <% end %>
    </p>
    <p>Views: <span><%= video.views %></span></p>
</div>

app/views/videos/_video_list.html.erb
<% @videos.each do |video| %>
    <%= render partial: "video_item", locals: { video: video } %>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<% content_for :additional_style do %>
  <%= stylesheet_link_tag 'datatable' %>
<% end %>
<% content_for :additional_script do %>
  <%= javascript_include_tag 'datatable' %>
<% end %>

<div class="datas" data-cont="<%= Video.order("views asc").select(:title, :href, :views).to_json %>"></div>
  <div class="row">
    <div class="col-lg-12">
        <div class="card-box">
            <div class="dropdown pull-right">
                <a href="#" class="dropdown-toggle card-drop" data-toggle="dropdown"
                   aria-expanded="false">
                    <i class="zmdi zmdi-more-vert"></i>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li><a href="#">Separated link</a></li>
                </ul>
            </div>

            <h4 class="header-title m-t-0 m-b-30">Combine Statistics</h4>

            <div id="combine-chart">
                <div id="website-stats" class="flot-chart" style="height: 320px;">
                </div>
            </div>

        </div>
    </div><!-- end col-->
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="card-box">
        <p class="text-muted m-b-15 font-13">
          <%= link_to 'Parse trends', "/videos/parse_trends", method: "get", class: "btn btn-info waves-effect w-md waves-light m-b-5" %>
          <%= link_to "Destroy all videos", videos_path, method: "delete", data: { confirm: "Are you sure?" }, class: "btn btn-danger  waves-effect w-md waves-light m-b-5" %>
        </p>
        <p class="m-t-20">
          <%= link_to "All categories", "/videos", class: "m-r-10" %>
          <% @categories.each do |c| %>
              <%= link_to c.name, "/videos?category_id=#{c.category_id}", class: "m-r-10" if c %>
          <% end %>
          <% if params[:category_id] %>
            | <%= link_to "Destroy all videos from this category", videos_path(category_id: params[:category_id]), method: "delete", data: { confirm: "Are you sure?" }, class: "m-l-10" %>
          <% end %>
        </p>
      </div>
    </div>
  </div>

  <div class="row videos"><%= render "video_list" %></div>
</div>


<%= javascript_include_tag 'float' %>
<script>
  var info = [], permit_to_scroll = true, page = 0;

  $(window).scroll(function() {
      if(($(window).scrollTop() + $(window).height() >= $(document).height() - 200) && permit_to_scroll) {
          page++;
          load_images();
      }
  })

  function load_images() {
     $.ajax({
            method: "GET",
            async: false,
            dataType: "HTML",
            url: "/videos/newitems",
            data: { "page": page },
            success: function(data, textStatus, request) {
                permit_to_scroll = (request.getResponseHeader('permit_to_scroll') == 'true');
                $(".videos").append(data);
            }
     });
  }

  function copyToClipboard(text) {
    window.prompt("Copy to clipboard: Ctrl+C, Enter", text);
  }

  function get_nums(){
    var arr = [];
    $.each($(".datas").data("cont"), function(index, value){
      var cur = $(this)[0];
      views = cur["views"];
      info.push({"link": cur["href"], "title": cur["title"]})
      arr.push([index, Number(views)]);
    })
    console.log(arr)
    return arr;
  }

  $(document).ready(function() {
    ! function($) {
        "use strict";

        var FlotChart = function() {
          this.$body = $("body")
          this.$realData = []
        };
        //creates plot graph
        FlotChart.prototype.createPlotGraph = function(selector, data1, labels, colors, borderColor, bgColor) {
          //shows tooltip
          $.plot($(selector), [{
            data : data1,
            label : labels[0],
            color : colors[0]
          }], {
            series : {
              lines : {
                show : true,
                fill : true,
                lineWidth : 3,
                fillColor : {
                  colors : [{
                    opacity : 0.4
                  }, {
                    opacity : 0.4
                  }]
                }
              },
              points : {
                show : false
              },
              shadowSize : 0
            },

            grid : {
              hoverable : true,
              clickable : true,
              borderColor : borderColor,
              tickColor : "#f9f9f9",
              borderWidth : 1,
              labelMargin : 10,
              backgroundColor : bgColor
            },
            legend : {
              position : "ne",
              margin : [0, -24],
              noColumns : 0,
              labelBoxBorderColor : null,
              labelFormatter : function(label, series) {
                // just add some space to labes
                return '' + label + '&nbsp;&nbsp;';
              },
              width : 30,
              height : 2
            },
            yaxis : {
              tickColor : 'transparent',
              tickLength: 0,
              font : {
                color : '#bdbdbd'
              }
            },
            xaxis : {
              tickColor : '#transparent',
              tickLength: 0,
              font : {
                color : '#bdbdbd'
              }
            },
            tooltip : true,
            tooltipOpts : {
              content : function(label, xval, yval, flotItem){
                var current = info[xval];
                return "Views: <b>"+yval+"</b><br/><span>" + current["title"] + "</span><br/><span>"+current["link"]+"</span>"
              },
              shifts : {
                x : -60,
                y : 25
              },
              defaultTheme : false
            }
          });
        },
        //end plot graph
        //initializing various charts and components
        FlotChart.prototype.init = function() {
          //plot graph data
          var uploads = get_nums();

          var plabels = ["Info", "Page views"];
          var pcolors = ['#188ae2', '#10c469'];
          var borderColor = 'transparent';
          var bgColor = 'transparent';
          this.createPlotGraph("#website-stats", uploads, plabels, pcolors, borderColor, bgColor);

          $("#website-stats").bind("plotclick", function (event, pos, item) {
            if (item) { 
                i = item["dataIndex"];
                var link = info[i]["link"];
                window.open(link, '_blank');
            }
          });
        },

        //init flotchart
        $.FlotChart = new FlotChart, $.FlotChart.Constructor =
        FlotChart

      }(window.jQuery),

      //initializing flotchart
      function($) {
        "use strict";
        $.FlotChart.init()
      }(window.jQuery);
  })
</script>

app/views/videos/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card-box">
      <div class="row">
        <%= form_for(@user) do |f| %>
          <div class="form-group m-b-20">
            <label class="col-sm-2 control-label">Name</label>
            <div class="col-sm-9"></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/videos/parse_trends.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card-box">
      <div class="row">
        <%= form_tag("/videos/get_video_info") do %>
            <%= fields_for :search do |f| %>
                <div class="form-group m-b-20">
                    <label class="col-sm-2 control-label">Поиск по фразе</label>
                    <div class="col-sm-9">
                        <%= f.text_field :q, class: "form-control inputmask" %>
                    </div>
                </div>

                <div class="form-group m-b-20">
                    <label class="col-sm-2 control-label">Категория</label>
                    <div class="col-sm-9">
                        <div class="row col-sm-12 m-t-10 m-b-10"><a href="#" class="latest-categories" data-categories="<%= @categories %>">Get latest categories</a></div>
                        <% Category.all.each do |c| %>
                            <div class="col-sm-4">
                                <%= check_box_tag 'category_ids[]', c.category_id, false %> <%= f.label :category_id, c.name %>
                            </div>
                        <% end %>
                    </div>
                </div>
            <% end %>
            <button class="btn btn-info col-sm-offset-2">Submit</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Channel:</strong>
  <%= @video.channel_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Href:</strong>
  <%= @video.href %>
</p>

<p>
  <strong>Views:</strong>
  <%= @video.views %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>

app/views/videos/success.html.erb
<script>
    function closeWindow() {
        window.open('', '_self', '');
        window.close();
    }
    setTimeout(closeWindow, 1);
</script>