config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: [:index] do
    post :parse_categories, on: :collection
  end

  scope path: '/enter', controller: 'enter' do 
    get :login
    post :check
    delete :destroy
  end

  resources :users

  scope path: "videos", controller: "videos" do
    get "/" => :index, as: "videos"
    get :newitems
    post :get_video_info
    get :parse_trends
    delete "/" => :destroy
  end

  get "success" => "videos#success"

  root :to => "enter#login"

end

app/models/category.rb
class Category < ActiveRecord::Base

	def self.parse_categories
        Category.destroy_all
		url = "https://gist.github.com/dgp/1b24bf2961521bd75d6c"
		html = open(url)
		doc = Nokogiri::HTML(html, nil, 'UTF-8')
		table = doc.css(".js-file-line-container")
		table.css("tr").each do |f|
			id, name = f.css("td")[1].text.split(" - ")
			Category.create(name: name, category_id: id.to_i)
            break if Category.all.count == 32
		end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :super_admin

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  def parse_categories
    Category.parse_categories
    redirect_to categories_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :category_id)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.number_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1></h1>

<div class="row">
  <div class="col-sm-12">
    <div class="card-box table-responsive">
      <div class="dropdown pull-right">
        <a href="#" class="dropdown-toggle card-drop" data-toggle="dropdown" aria-expanded="false">
            <i class="zmdi zmdi-more-vert"></i>
        </a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
        </ul>
      </div>

      <%= link_to 'Parse categories', parse_categories_categories_path, method: :post %>

      <h4 class="header-title m-t-0 m-b-30">Listing Categories</h4>
      <table id="datatable-buttons" class="table table-striped table-bordered" data-page-length='50'>
        <thead>
          <tr>
            <th>Name</th>
            <th>Category</th>
          </tr>
        </thead>

        <tbody>
          <% @categories.each do |category| %>
            <tr>
              <td><%= category.name %></td>
              <td><%= category.category_id %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @category.category_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>